/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import model from './ramen.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.07, 0.88, 0.73]}>
        <group position={[-0.07, 0.96, 0.66]} rotation={[0.51, 0, 0]}>
          <group position={[-0.08, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.15, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.22, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.3, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.38, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.45, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.52, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.6, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.68, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.75, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.82, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.9, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[-0.98, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.08, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.15, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.22, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.3, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.38, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.45, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.52, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.6, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.68, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.75, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.82, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.9, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <group position={[0.98, 0, 0]}>
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile7.geometry}
              position={[0, 0.04, 0.35]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile6.geometry}
              position={[0, 0.03, 0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile5.geometry}
              position={[0, 0.02, 0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile4.geometry}
              position={[0, 0.01, 0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile3.geometry}
              position={[0, -0.01, -0.05]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile2.geometry}
              position={[0, -0.02, -0.15]}
              rotation={[0, 0, 0]}
            />
            <mesh
              material={materials.Grey}
              geometry={nodes.Tile1.geometry}
              position={[0, -0.03, -0.25]}
              rotation={[0, 0, 0]}
            />
            <mesh material={materials.Grey} geometry={nodes.Tile.geometry} position={[0, -0.04, -0.35]} />
            <mesh material={materials.Grey} geometry={nodes.Wood.geometry} position={[0, -0.04, -0.36]} />
          </group>
          <mesh
            material={materials.Grey}
            geometry={nodes.Overhang.geometry}
            position={[0, -0.02, -0.01]}
            rotation={[-0.12, 0, 0]}
          />
        </group>
        <group position={[-0.29, -0.12, 0.2]} rotation={[0, 0.53, 0]}>
          <mesh
            material={materials.Black}
            geometry={nodes.Chopstick1.geometry}
            position={[-0.05, 0, 0.01]}
            rotation={[0.13, 0.13, -2.21]}
          />
          <mesh
            material={materials.Black}
            geometry={nodes.Chopstick.geometry}
            position={[-0.04, 0, -0.01]}
            rotation={[-0.02, -0.02, -2.2]}
          />
          <mesh
            material={materials.Grey}
            geometry={nodes.Bowl.geometry}
            position={[0.04, 0.01, 0]}
            rotation={[0, -0.66, -Math.PI]}
          />
          <mesh material={materials.Red} geometry={nodes.Broth.geometry} position={[0.04, -0.01, 0]} />
        </group>
        <group position={[0.11, -0.12, 0.2]} rotation={[0, -Math.PI / 9, 0]}>
          <mesh
            material={materials.Black}
            geometry={nodes.Chopstick1.geometry}
            position={[-0.05, 0, 0.01]}
            rotation={[0.09, 0.17, -2.4]}
          />
          <mesh
            material={materials.Black}
            geometry={nodes.Chopstick.geometry}
            position={[-0.04, 0, -0.01]}
            rotation={[-1.96, 0.77, -1.33]}
          />
          <mesh
            material={materials.Grey}
            geometry={nodes.Bowl.geometry}
            position={[0.04, 0.01, 0]}
            rotation={[0, -0.57, -Math.PI]}
          />
          <mesh material={materials.Red} geometry={nodes.Broth.geometry} position={[0.04, -0.01, 0]} />
        </group>
        <group position={[0.51, -0.12, 0.2]}>
          <mesh
            material={materials.Black}
            geometry={nodes.Chopstick1.geometry}
            position={[-0.05, 0, 0.01]}
            rotation={[0.06, 0.05, -2.37]}
          />
          <mesh
            material={materials.Black}
            geometry={nodes.Chopstick.geometry}
            position={[-0.04, 0, -0.01]}
            rotation={[-0.02, -0.02, -2.37]}
          />
          <mesh
            material={materials.Grey}
            geometry={nodes.Bowl.geometry}
            position={[0.04, 0.01, 0]}
            rotation={[0, 0, -Math.PI]}
          />
          <mesh material={materials.Red} geometry={nodes.Broth.geometry} position={[0.04, -0.01, 0]} />
        </group>
        <group position={[-0.22, -0.64, 0.77]}>
          <mesh material={materials.Black} geometry={nodes.Pole.geometry} position={[0, -0.09, 0]} />
          <mesh material={nodes.Floor.material} geometry={nodes.Floor.geometry} position={[0, -0.23, 0]} />
          <mesh material={materials.Red} geometry={nodes.Seat.geometry} position={[0, 0.09, 0]} />
        </group>
        <group position={[0.18, -0.64, 0.77]}>
          <mesh material={materials.Black} geometry={nodes.Pole.geometry} position={[0, -0.1, 0]} />
          <mesh material={nodes.Floor.material} geometry={nodes.Floor.geometry} position={[0, -0.23, 0]} />
          <mesh material={materials.Red} geometry={nodes.Seat.geometry} position={[0, 0.09, 0]} />
        </group>
        <group position={[0.58, -0.64, 0.77]}>
          <mesh material={materials.Black} geometry={nodes.Pole.geometry} position={[0, -0.09, 0]} />
          <mesh material={nodes.Floor.material} geometry={nodes.Floor.geometry} position={[0, -0.23, 0]} />
          <mesh material={materials.Red} geometry={nodes.Seat.geometry} position={[0, 0.09, 0]} />
        </group>
        <group position={[-0.92, 0.54, 0.78]}>
          <mesh material={nodes.String.material} geometry={nodes.String.geometry} position={[0, 0.19, 0]} />
          <mesh material={materials.Black} geometry={nodes.Middle_bit.geometry} position={[0, -0.3, 0]} />
          <mesh material={materials.Red} geometry={nodes.Lantern.geometry} position={[0, -0.3, 0]} />
        </group>
        <group position={[-0.47, 0.57, 0.78]}>
          <mesh material={materials.Black} geometry={nodes.String.geometry} position={[0, 0.19, 0]} />
          <mesh material={materials.Black} geometry={nodes.Middle_bit.geometry} position={[0, -0.1, 0]} />
          <mesh material={materials.Red} geometry={nodes.Lantern.geometry} position={[0, -0.1, 0]} />
        </group>
        <group position={[-0.07, 0.57, 0.78]}>
          <mesh material={materials.Black} geometry={nodes.String.geometry} position={[0, 0.19, 0]} />
          <mesh material={materials.Black} geometry={nodes.Middle_bit.geometry} position={[0, -0.1, 0]} />
          <mesh material={materials.Red} geometry={nodes.Lantern.geometry} position={[0, -0.1, 0]} />
        </group>
        <group position={[0.33, 0.57, 0.78]}>
          <mesh material={materials.Black} geometry={nodes.String.geometry} position={[0, 0.19, 0]} />
          <mesh material={materials.Black} geometry={nodes.Middle_bit.geometry} position={[0, -0.1, 0]} />
          <mesh material={materials.Red} geometry={nodes.Lantern.geometry} position={[0, -0.1, 0]} />
        </group>
        <group position={[0.73, 0.57, 0.78]}>
          <mesh material={materials.Black} geometry={nodes.String.geometry} position={[0, 0.19, 0]} />
          <mesh material={materials.Black} geometry={nodes.Middle_bit.geometry} position={[0, -0.1, 0]} />
          <mesh material={materials.Red} geometry={nodes.Lantern.geometry} position={[0, -0.1, 0]} />
        </group>
        <group position={[-0.07, 0.12, -0.64]}>
          <mesh material={materials.Black} geometry={nodes.Shlap9.geometry} position={[0, -0.9, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap8.geometry} position={[0, -0.7, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap7.geometry} position={[0, -0.5, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap6.geometry} position={[0, -0.3, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap5.geometry} position={[0, -0.1, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap4.geometry} position={[0, 0.9, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap3.geometry} position={[0, 0.7, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap2.geometry} position={[0, 0.5, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap1.geometry} position={[0, 0.3, 0]} />
          <mesh material={materials.Black} geometry={nodes.Shlap.geometry} position={[0, 0.1, 0]} />
        </group>
        <mesh
          material={materials.White}
          geometry={nodes.Cube.geometry}
          position={[-0.07, 1.21, 0.69]}
          rotation={[0.47, 0, 0]}
        />
        <mesh material={materials.White} geometry={nodes.Table_Top.geometry} position={[0.13, -0.23, 0.07]} />
        <mesh material={materials.Black} geometry={nodes.Table.geometry} position={[0.18, -0.54, -0.01]} />
        <mesh material={materials.Grey} geometry={nodes.M_Wall.geometry} position={[-0.07, 0.12, -0.73]} />
        <mesh material={materials.Grey} geometry={nodes.L_Wall.geometry} position={[-1.02, 0.12, -0.73]} />
        <mesh material={materials.Grey} geometry={nodes.R_Wall.geometry} position={[0.88, 0.12, -0.73]} />
        <mesh material={materials.Grey} geometry={nodes.Ceiling.geometry} position={[-0.07, 1.12, -0.73]} />
        <mesh material={materials.Grey} geometry={nodes.Floor.geometry} position={[-0.07, -0.88, -0.73]} />
      </group>
    </group>
  )
}
