/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import model from './tree.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.01, 0.66, -0.01]} scale={[0.84, 0.84, 0.84]}>
        <mesh castShadow material={materials.Trunk} geometry={nodes.Cylinder.geometry} position={[0, -0.47, 0]} />
      </group>
      <mesh castShadow material={materials.Tree} geometry={nodes.Leaves.geometry} position={[-0.01, 0.59, -0.01]} />
    </group>
  )
}
