/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import model from './pine-tree.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.01, 0.66, -0.01]} scale={[0.84, 0.84, 0.84]}>
        <mesh material={materials.Trunk} geometry={nodes.Cylinder.geometry} position={[0, -0.47, 0]} />
      </group>
      <mesh material={materials['Pine Tree']} geometry={nodes.Cone2.geometry} position={[0, 0.83, 0]} />
      <mesh material={materials['Pine Tree']} geometry={nodes.Cone1.geometry} position={[0, 0.65, 0]} />
      <mesh material={materials['Pine Tree']} geometry={nodes.Cone.geometry} position={[0, 0.45, 0]} />
    </group>
  )
}
