/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import model from './three-floor-building.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 1.57, 0]}>
        {/* <group position={[0.01, 0.79, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
          <group position={[0.39, 0.76, -0.13]} rotation={[0, 1.57, 0]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.39, -0.11, 0.13]} rotation={[0, 1.57, 0]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.39, -0.57, -0.05]} rotation={[0, 1.57, 0]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.19, -0.57, -0.36]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.13, 0.26, -0.36]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.17, 0.38, -0.36]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.37, 0.43, -0.13]} rotation={[0, -1.57, 0]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.37, -0.09, 0.19]} rotation={[0, -1.57, 0]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.37, -0.23, -0.15]} rotation={[0, -1.57, 0]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.18, -0.58, 0.4]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.15, 0.39, 0.4]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.06, -0.08, 0.4]}>
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials['Darker Yellow']} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
        </group> */}
        <group position={[-0.24, 1.77, 0.18]} rotation={[0, 0, 0]}>
          <mesh
            material={materials.White}
            geometry={nodes.AC_Unit.geometry}
            position={[0.49, -0.03, -0.19]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube8.geometry}
            position={[0, 0.04, 0.08]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube7.geometry}
            position={[0, -0.01, 0.08]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube6.geometry}
            position={[0, -0.01, 0]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube5.geometry}
            position={[0, 0.04, 0]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube4.geometry}
            position={[0, 0.01, -0.08]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube3.geometry}
            position={[0, -0.02, -0.08]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube.geometry}
            position={[0, -0.05, 0]}
            rotation={[0, 0, 0]}
          />
        </group>
        <mesh
          material={materials.White}
          geometry={nodes.Rail.geometry}
          position={[-0.13, 0.08, -0.47]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Rail1.geometry}
          position={[0.13, 0.08, -0.47]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Step1.geometry}
          position={[0, 0.02, -0.47]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Base.geometry}
          position={[0, 0.06, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Step2.geometry}
          position={[0, 0.06, -0.44]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Roof1.geometry}
          position={[0, 1.64, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Roof2.geometry}
          position={[0, 1.67, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Window_Edges.geometry}
          position={[0, 0.87, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Cube1.geometry}
          position={[0, 1.12, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Cube2.geometry}
          position={[0, 0.62, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.Yellow}
          geometry={nodes.Building.geometry}
          position={[0, 0.87, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.Yellow}
          geometry={nodes.Door.geometry}
          position={[0, 0.87, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.Windows}
          geometry={nodes.Windows.geometry}
          position={[0, 0.87, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </group>
    </group>
  )
}
