/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import model from './office-floor-b.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.15, 0]}>
        <mesh material={materials.White} geometry={nodes.Top.geometry} position={[0, 0.15, 0]} />
        <mesh material={materials.White} geometry={nodes.Bottom.geometry} position={[0, -0.15, 0]} />
        <mesh material={materials.Windows} geometry={nodes.Windows.geometry} />
      </group>
    </group>
  )
}
