/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import model from './flower.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.09, 0]}>
        <group position={[0, 0, 0]} rotation={[-0.44, 0, 0]}>
          <mesh material={materials.Red} geometry={nodes.Petal.geometry} position={[0, 0, 0.02]} />
        </group>
        <group position={[0, 0, 0]} rotation={[-0.99, 1.04, 0.92]}>
          <mesh material={materials.Red} geometry={nodes.Petal.geometry} position={[0, 0, 0.02]} />
        </group>
        <group position={[0, 0, 0]} rotation={[-2.62, 0.56, 2.84]}>
          <mesh material={materials.Red} geometry={nodes.Petal.geometry} position={[0, 0, 0.02]} />
        </group>
        <group position={[0, 0, 0]} rotation={[-2.62, -0.56, -2.84]}>
          <mesh material={materials.Red} geometry={nodes.Petal.geometry} position={[0, 0, 0.02]} />
        </group>
        <group position={[0, 0, 0]} rotation={[-0.99, -1.04, -0.92]}>
          <mesh material={materials.Red} geometry={nodes.Petal.geometry} position={[0, 0, 0.02]} />
        </group>
      </group>
      <mesh material={materials.White} geometry={nodes.Stigma.geometry} position={[0, 0.09, 0]} />
      <mesh material={materials.Green} geometry={nodes.Stem.geometry} position={[0, 0.04, 0]} />
    </group>
  )
}
