/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import model from './two-floor-building.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 1.57, 0]}>
        {/* <group position={[-0.15, 0.67, 0.02]} rotation={[-Math.PI, 0, -Math.PI]}>
          <group position={[0.35, -0.02, 0.18]} rotation={[0, 1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.39, -0.55, -0.05]} rotation={[0, 1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.12, -0.17, -0.36]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.45, 0.01, -0.33]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.17, 0.37, -0.33]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.37, 0.38, -0.07]} rotation={[0, -1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.37, -0.14, 0.19]} rotation={[0, -1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.37, -0.54, -0.15]} rotation={[0, -1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.1, -0.54, 0.4]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.56, -0.16, 0.4]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.08, 0.38, 0.38]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.23, -0.03, 0.38]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.7, -0.01, 0.23]} rotation={[0, -1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.7, 0.36, -0.17]} rotation={[0, -1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[0.35, 0.35, -0.17]} rotation={[0, 1.57, 0]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.29, -0.54, -0.36]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
          <group position={[-0.53, 0, 0.38]}>
            <mesh material={materials.Bricks} geometry={nodes.Cube4.geometry} position={[0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube3.geometry} position={[-0.02, -0.01, 0]} />
            <mesh material={materials.Bricks} geometry={nodes.Cube.geometry} position={[0, 0.01, 0]} />
          </group>
        </group> */}
        <group position={[-0.13, 1.24, 0.16]} rotation={[0, 0, 0]}>
          <mesh
            material={materials.White}
            geometry={nodes.AC_Unit.geometry}
            position={[0.45, -0.03, -0.18]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Yellow']}
            geometry={nodes.AC_Unit1.geometry}
            position={[0.45, 0.01, -0.18]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube8.geometry}
            position={[-0.19, 0.04, -0.09]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube7.geometry}
            position={[-0.19, 0, -0.09]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube6.geometry}
            position={[-0.19, 0, -0.16]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube5.geometry}
            position={[-0.19, 0.04, -0.16]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube4.geometry}
            position={[-0.19, 0.02, -0.24]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube3.geometry}
            position={[-0.19, -0.02, -0.24]}
            rotation={[0, 0, 0]}
          />
          <mesh
            material={materials['Light Grey']}
            geometry={nodes.Cube.geometry}
            position={[-0.19, -0.05, -0.17]}
            rotation={[0, 0, 0]}
          />
        </group>
        <mesh
          material={materials.White}
          geometry={nodes.Roof1.geometry}
          position={[0.02, 1.14, 0.01]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Roof2.geometry}
          position={[0.02, 1.19, 0.01]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Cube2.geometry}
          position={[0.02, 0.57, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Roof_Top.geometry}
          position={[0.02, 1.19, 0.01]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.White}
          geometry={nodes.Door.geometry}
          position={[0.02, 0.55, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['Light Yellow']}
          geometry={nodes.Building.geometry}
          position={[0.02, 0.55, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['Light Yellow']}
          geometry={nodes.Window_Middles.geometry}
          position={[0.02, 0.55, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['Light Yellow']}
          geometry={nodes.Window_Edges.geometry}
          position={[0.02, 0.55, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['Light Yellow']}
          geometry={nodes.Base.geometry}
          position={[-0.16, 0.04, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials['Building Bottom']}
          geometry={nodes.Building_Bottom.geometry}
          position={[0.02, 0.55, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
        <mesh
          material={materials.Windows}
          geometry={nodes.Windows.geometry}
          position={[0.02, 0.55, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
        />
      </group>
    </group>
  )
}
