/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useLoader } from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

import model from './clouds.gltf'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useLoader(GLTFLoader, model)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-4.87, -0.56, -2.55]} rotation={[0, 1.57, 0]}>
        <mesh material={materials.Clouds} geometry={nodes.Sphere.geometry} position={[0.01, -0.05, -0.3]} />
        <mesh material={materials.Clouds} geometry={nodes.Sphere1.geometry} position={[0.02, 0.05, 0.01]} />
        <mesh material={materials.Clouds} geometry={nodes.Sphere2.geometry} position={[-0.03, 0, 0.28]} />
      </group>
      <group position={[2.44, -0.56, -2.55]} rotation={[0, 1.57, 0]}>
        <mesh material={materials.Clouds} geometry={nodes.Sphere1.geometry} position={[0.01, 0.04, 0.01]} />
        <mesh material={materials.Clouds} geometry={nodes.Sphere2.geometry} position={[-0.02, 0, 0.2]} />
      </group>
    </group>
  )
}
